export enum Min {
  USERNAME = 3,
  QUESTION_TEXT = 10,
  ANSWER_TEXT = 1,
  CATEGORY_NAME = 2,
  CATEGORY_DESCRIPTION = 5,
  QUIZ_TITLE = 5,
  QUIZ_DESCRIPTION = 10,
  QUESTIONS_PER_QUIZ = 5,
  DIFFICULTY_NAME = 3,
}

export enum Max {
  USERNAME = 16,
  QUESTION_TEXT = 256,
  ANSWER_TEXT = 128,
  CATEGORY_NAME = 32,
  CATEGORY_DESCRIPTION = 64,
  QUIZ_TITLE = 64,
  QUIZ_DESCRIPTION = 128,
  DIFFICULTY_NAME = 16,
}
